version: '2'
services:  
  
  api:
    container_name: todo-api
    build: .
    # command: node dist/apps/api/main.js
    command: nest start --debug 0.0.0.0:9229 --watch api
    ports:
      - 3124:3000
  mysql:
    image: mysql:5.7
    restart: always
    platform: linux/amd64
    environment:
      MYSQL_DATABASE: "wallet_cpl"
      # Password for root access
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_TCP_PORT: 3306
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - 33056:3306
      # Where our data will be persisted
    volumes:
      - mysqldb:/var/lib/mysql
      - ./dump:/docker-entrypoint-initdb.d

volumes:
  mysqldb: 
    name: mysqldb